### ISSUE TITLE
Question in auth-http-interceptor.ts redirect

### ISSUE THREAD

**Issue by craigeddy** [duluca/lemon-mart#13]
Should 
```
        if (err.status === 401) {
          this.router.navigate(['/user/login'], {
            queryParams: { redirectUrl: this.router.routerState.snapshot.url },
          })
        }
```
be
```
        if (err.status === 401) {
          this.router.navigate(['/login'], {
            queryParams: { redirectUrl: this.router.routerState.snapshot.url },
          })
        }
```
I don't think the login route is `/user/login` unless I'm missing/mis-understanding something.

**Comment by duluca** [comment]
@craigeddy You're correct! It is fixed now. Thanks a bunch for the report.

**Comment by craigeddy** [comment]
@duluca You bet! We have a couple copies of your book laying around the office and they're constantly being referenced. :)

Need to get together soon for a beer or two.

**Comment by duluca** [comment]
@craigeddy Love it. Thank you. I would definitely appreciate a couple of reviews on Amazon🍻
