### ISSUE TITLE
just downloaded beta version

### ISSUE THREAD

**Issue by dj7918** [duluca/lemon-mart#19]
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.

**Comment by duluca** [comment]
@dj7918 is this on update-to-ng8 branch? If so please try again

**Comment by duluca** [comment]
The app is now on Angular 9 on the master branch, please re-open if you're experiencing issues.
