### ISSUE TITLE
Error in auth.firebase.service.ts when Circelci builds the project

### ISSUE THREAD

**Issue by walidBouguima** [duluca/lemon-mart#31]
`ERROR in src/app/auth/auth.firebase.service.ts:55:34 - error TS2345: Argument of type 'OperatorFunction<firebase.User, User>' is not assignable to parameter of type 'OperatorFunction<User | null, User>'.
  Type 'User | null' is not assignable to type 'User'.
    Type 'null' is not assignable to type 'User'.

55     return this.afAuth.user.pipe(map(this.transformFirebaseUser))
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by duluca** [comment]
@walidBouguima I'm unable to replicate this issue. See PR #35, which builds successfully. Please re-open if you can replicate it
